title: MAPLE
description: AI 기반 기타 연주 실시간 분석 및 피드백 시스템

remote_theme: thedevslot/WhatATheme
plugins:
  - jekyll-remote-theme
  - jekyll-feed

markdown: kramdown

url: "https://kookmin-sw.github.io"
baseurl: "/capstone-2025-05"

heroimage: /assets/guitar.jpg

author-name: Capstone Team
author-url: https://github.com/kookmin-sw/capstone-2025-05

permalink: "blog/:title"
