title: MAPLE
description: AI 기반 기타 연주 실시간 분석 및 피드백 시스템

remote_theme: thedevslot/WhatATheme

url: "https://kookmin-sw.github.io"
baseurl: "/capstone-2025-05"
favicon-url: "https://kookmin-sw.github.io/capstone-2025-05/assets/favicon.png"

heroimage: "https://kookmin-sw.github.io/capstone-2025-05/assets/guitar.jpg"

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed

permalink: "blog/:title"
