title: MAPLE
description: AI 기반 기타 연주 실시간 분석 및 피드백 시스템

remote_theme: thedevslot/WhatATheme

url: "https://kookmin-sw.github.io"
baseurl: "/capstone-2025-05"

heroimage: "https://kookmin-sw.github.io/capstone-2025-05/assets/guitar.jpg"

author-name: Team 05
author-url: https://github.com/kookmin-sw/capstone-2025-05

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed

permalink: "blog/:title"
