FROM node:20 AS build

# build-args 전달받기
ARG REACT_APP_SPOTIFY_CLIENT_ID
ARG REACT_APP_SPOTIFY_CLIENT_SECRET
ARG REACT_APP_SPOTIFY_REDIRECT_URI
ARG REACT_APP_API_DATABASE_URL
ARG REACT_APP_CLIENT_ID
ARG REACT_APP_REDIRECT_URI
ARG REACT_APP_SCOPE
ARG PUBLIC_URL
ARG REACT_APP_AUDIO_URL
ARG REACT_APP_RESULT_URL

#환경 변수로 설정 (CRA 빌드에 필요)
ENV REACT_APP_SPOTIFY_CLIENT_ID=$REACT_APP_SPOTIFY_CLIENT_ID
ENV REACT_APP_SPOTIFY_CLIENT_SECRET=$REACT_APP_SPOTIFY_CLIENT_SECRET
ENV REACT_APP_SPOTIFY_REDIRECT_URI=$REACT_APP_SPOTIFY_REDIRECT_URI
ENV REACT_APP_API_DATABASE_URL=$REACT_APP_API_DATABASE_URL
ENV REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID
ENV REACT_APP_REDIRECT_URI=$REACT_APP_REDIRECT_URI
ENV REACT_APP_SCOPE=$REACT_APP_SCOPE
ENV REACT_APP_RESULT_URL=$REACT_APP_RESULT_URL
ENV REACT_APP_AUDIO_URL=$REACT_APP_AUDIO_URL
ENV PUBLIC_URL=$PUBLIC_URL

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
