version: '3'

services:
  maple-media-api:
    build: .
    container_name: maple-media-api
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/app/app/static
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul 