version: '3.8'

services:
  maple-media-api:
    build: .
    container_name: maple-media-api
    ports:
      - "8000:8000"
    volumes:
      - ./app/static:/app/app/static
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: maple-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: 

networks:
  default:
    name: maple-network
    driver: bridge