services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # nginx.conf를 올바른 위치에 마운트
    depends_on:
      - client
      - api
      - analysis_api
      - media_server
    networks:
      - maple-network
  client:
    image: ${DOCKER_USERNAME}/maple-client:latest
    env_file:
      - .env
    networks:
      - maple-network
  api:
    image: ${DOCKER_USERNAME}/maple-api:latest
    env_file:
      - .env
    networks:
      - maple-network
  
  # Analysis server components
  analysis_api:
    image: ${DOCKER_USERNAME}/maple-analysis-service:latest
    env_file:
      - analysis.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=maple_audio_db
    networks:
      - maple-network
    depends_on:
      - redis
      - mongo
  
  analysis_worker:
    image: ${DOCKER_USERNAME}/maple-analysis-service:latest
    command: celery -A workers.tasks worker -l info
    env_file:
      - analysis.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=maple_audio_db
    networks:
      - maple-network
    depends_on:
      - redis
      - mongo
  
  redis:
    image: redis:7-alpine
    networks:
      - maple-network
  
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - maple-network

  media_server:
    image: ${DOCKER_USERNAME}/maple-media-server:latest
    networks:
      - maple-network

volumes:
  mongo_data:

networks:
  maple-network:
    driver: bridge