name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build Projucer
      run: |
        echo "Building Projucer..."
        cd JUCE\extras\Projucer\Builds\VisualStudio2022
        msbuild Projucer.sln /p:Configuration=Release /p:Platform=x64
        
    - name: Generate Solution
      run: |
        $PROJUCER_PATH = ".\JUCE\extras\Projucer\Builds\VisualStudio2022\x64\Release\App\Projucer.exe"
        echo "Using Projucer at: $PROJUCER_PATH"
        & $PROJUCER_PATH --resave "MAPLE.jucer"
        
    - name: Build Solution
      run: |
        msbuild /m /p:Configuration=Release "Builds\VisualStudio2022\MAPLE.sln"