name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Builds\VisualStudio2022\MAPLE.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Check Solution Path
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
        echo "Checking Builds directory:"
        if (Test-Path "Builds") {
          echo "Builds directory exists"
          dir Builds
        } else {
          echo "Builds directory not found"
        }
        if (Test-Path ${{env.SOLUTION_FILE_PATH}}) {
          echo "Solution file found"
        } else {
          echo "Solution file not found"
          exit 1
        }

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}