name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Builds\VisualStudio2022\MAPLE.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup JUCE
      run: |
        echo "Downloading JUCE..."
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-windows.zip" -OutFile "juce.zip"
        
        echo "Extracting JUCE..."
        Expand-Archive -Path "juce.zip" -DestinationPath "JUCE" -Force
        
        # Projucer 찾기
        $PROJUCER_PATH = Get-ChildItem -Path "JUCE" -Recurse -Filter "Projucer.exe" | Select-Object -First 1 -ExpandProperty FullName
        
        if ($PROJUCER_PATH) {
            echo "Found Projucer at: $PROJUCER_PATH"
            
            # JUCE 모듈 경로 설정
            $JUCE_MODULES_PATH = "D:\a\maple-client-desktop\maple-client-desktop\JUCE\JUCE\modules"
            echo "Setting JUCE modules path: $JUCE_MODULES_PATH"
            & $PROJUCER_PATH --set-global-search-path windows defaultJuceModulePath "$JUCE_MODULES_PATH"
            
            echo "Generating Visual Studio solution..."
            & $PROJUCER_PATH --resave "MAPLE.jucer"
            
            # 솔루션 파일이 생성되었는지 확인
            if (Test-Path "Builds\VisualStudio2022\MAPLE.sln") {
                echo "Solution file generated successfully"
            } else {
                echo "Solution file not found after generation"
                exit 1
            }
        } else {
            echo "Projucer.exe not found in extracted files"
            exit 1
        }

    - name: Check Solution Path
      run: |
        echo "Checking solution file..."
        if (Test-Path ${{env.SOLUTION_FILE_PATH}}) {
            echo "Solution file exists at: ${{env.SOLUTION_FILE_PATH}}"
            dir Builds\VisualStudio2022
        } else {
            echo "Solution file not found at: ${{env.SOLUTION_FILE_PATH}}"
            exit 1
        }

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}