name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Download Projucer
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/8.0.6/juce-8.0.6-windows.zip" -OutFile "juce-windows.zip"
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $zip = [System.IO.Compression.ZipFile]::OpenRead("juce-windows.zip")
        $projucerEntry = $zip.Entries | Where-Object { $_.Name -eq "Projucer.exe" }
        [System.IO.Compression.ZipFileExtensions]::ExtractToFile($projucerEntry, ".\Projucer.exe", $true)
        $zip.Dispose()
        
    - name: Generate Solution
      run: |
        $PROJUCER_PATH = ".\Projucer.exe"
        echo "Using Projucer at: $PROJUCER_PATH"
        & $PROJUCER_PATH --resave "MAPLE.jucer"
        
    - name: Build Solution
      run: |
        msbuild /m /p:Configuration=Release "Builds\VisualStudio2022\MAPLE.sln"