name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Builds\VisualStudio2022\MAPLE.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download Projucer
      run: |
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-windows.zip" -OutFile "juce.zip"
        Expand-Archive -Path "juce.zip" -DestinationPath "D:\a\maple-client-desktop\maple-client-desktop\JUCE"

    - name: Generate Visual Studio Solution
      run: |
        $PROJUCER_PATH = "D:\a\maple-client-desktop\maple-client-desktop\JUCE\JUCE\Projucer.exe"
        echo "Projucer path: $PROJUCER_PATH"
        if (Test-Path $PROJUCER_PATH) {
            echo "Projucer exists at specified path"
        } else {
            echo "Projucer not found at specified path"
            echo "Listing JUCE directory contents:"
            dir "D:\a\maple-client-desktop\maple-client-desktop\JUCE" -Recurse
            exit 1
        }
        & $PROJUCER_PATH --resave "MAPLE.jucer"

    - name: Check Solution Path
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
        echo "Checking Builds directory:"
        if (Test-Path "Builds") {
          echo "Builds directory exists"
          dir Builds
        } else {
          echo "Builds directory not found"
        }
        if (Test-Path ${{env.SOLUTION_FILE_PATH}}) {
          echo "Solution file found"
        } else {
          echo "Solution file not found"
          exit 1
        }

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}