name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Download Projucer
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-windows.zip" -OutFile "juce-windows.zip"
        Expand-Archive -Path "juce-windows.zip" -DestinationPath "."
        
    - name: Generate Solution
      run: |
        $PROJUCER_PATH = ".\JUCE\Projucer.exe"
        echo "Using Projucer at: $PROJUCER_PATH"
        & $PROJUCER_PATH --resave "MAPLE.jucer"
        
    - name: Build Solution
      run: |
        msbuild /m /p:Configuration=Release "Builds\VisualStudio2022\MAPLE.sln"