name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive  # JUCE 서브모듈을 포함하여 모든 서브모듈을 가져옵니다
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Generate Solution
      run: |
        # Projucer로 솔루션 생성
        $PROJUCER_PATH = ".\JUCE\extras\Projucer\Builds\VisualStudio2022\x64\Debug\App\Projucer.exe"
        & $PROJUCER_PATH --resave "MAPLE.jucer"
        
    - name: Build Solution
      run: |
        msbuild /m /p:Configuration=Release "Builds\VisualStudio2022\MAPLE.sln"