name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Builds\VisualStudio2022\MAPLE.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup JUCE
      run: |
        echo "Downloading JUCE..."
        Invoke-WebRequest -Uri "https://github.com/juce-framework/JUCE/releases/download/7.0.9/juce-7.0.9-windows.zip" -OutFile "juce.zip"
        
        echo "Extracting JUCE..."
        Expand-Archive -Path "juce.zip" -DestinationPath "JUCE" -Force
        
        # Projucer 찾기
        $PROJUCER_PATH = Get-ChildItem -Path "JUCE" -Recurse -Filter "Projucer.exe" | Select-Object -First 1 -ExpandProperty FullName
        $JUCE_MODULES_PATH = "D:\a\maple-client-desktop\maple-client-desktop\JUCE\JUCE\modules"
        
        if ($PROJUCER_PATH) {
            echo "Found Projucer at: $PROJUCER_PATH"
            
            # .jucer 파일 수정
            $jucer_content = @"
<?xml version="1.0" encoding="UTF-8"?>
<JUCERPROJECT id="YOUR_PROJECT_ID" name="MAPLE" projectType="guiapp" useAppConfig="0"
              addUsingNamespaceToJuceHeader="0" jucerFormatVersion="1">
  <MAINGROUP id="YOUR_GROUP_ID" name="MAPLE">
    <GROUP id="Source" name="Source">
      <GROUP id="App" name="App">
        <FILE id="Main" name="Main.cpp" compile="1" resource="0" file="Source/App/Main.cpp"/>
      </GROUP>
      <GROUP id="Components" name="Components">
        <FILE id="MainComponent" name="MainComponent.cpp" compile="1" resource="0"
              file="Source/Components/MainComponent.cpp"/>
        <FILE id="MainComponent" name="MainComponent.h" compile="0" resource="0"
              file="Source/Components/MainComponent.h"/>
        <GROUP id="Navigation" name="Navigation">
          <FILE id="SidebarComponent" name="SidebarComponent.cpp" compile="1" resource="0"
                file="Source/Components/Navigation/SidebarComponent.cpp"/>
          <FILE id="SidebarComponent" name="SidebarComponent.h" compile="0" resource="0"
                file="Source/Components/Navigation/SidebarComponent.h"/>
        </GROUP>
        <GROUP id="Pages" name="Pages">
          <FILE id="HomePage" name="HomePage.cpp" compile="1" resource="0"
                file="Source/Components/Pages/HomePage.cpp"/>
          <FILE id="HomePage" name="HomePage.h" compile="0" resource="0"
                file="Source/Components/Pages/HomePage.h"/>
        </GROUP>
      </GROUP>
      <GROUP id="Utils" name="Utils">
        <FILE id="Constants" name="Constants.h" compile="0" resource="0"
              file="Source/Utils/Constants.h"/>
      </GROUP>
    </GROUP>
  </MAINGROUP>
  <MODULES>
    <MODULE id="juce_core" showAllCode="1" useLocalCopy="0" useGlobalPath="1"/>
    <MODULE id="juce_data_structures" showAllCode="1" useLocalCopy="0" useGlobalPath="1"/>
    <MODULE id="juce_events" showAllCode="1" useLocalCopy="0" useGlobalPath="1"/>
    <MODULE id="juce_graphics" showAllCode="1" useLocalCopy="0" useGlobalPath="1"/>
    <MODULE id="juce_gui_basics" showAllCode="1" useLocalCopy="0" useGlobalPath="1"/>
  </MODULES>
  <EXPORTFORMATS>
    <XCODE_MAC targetFolder="Builds/MacOSX">
      <CONFIGURATIONS>
        <CONFIGURATION isDebug="1" name="Debug"/>
        <CONFIGURATION isDebug="0" name="Release"/>
      </CONFIGURATIONS>
    </XCODE_MAC>
    <VS2022 targetFolder="Builds/VisualStudio2022">
      <CONFIGURATIONS>
        <CONFIGURATION isDebug="1" name="Debug"/>
        <CONFIGURATION isDebug="0" name="Release"/>
      </CONFIGURATIONS>
    </VS2022>
  </EXPORTFORMATS>
  <JUCEOPTIONS JUCE_STRICT_REFCOUNTEDPOINTER="1" JUCE_VST3_CAN_REPLACE_VST2="0"/>
</JUCERPROJECT>
"@
            
            # 수정된 내용 저장
            $jucer_content | Set-Content "MAPLE.jucer" -NoNewline
            
            echo "Modified .jucer file content:"
            Get-Content "MAPLE.jucer"
            
            # Projucer 전역 설정
            & $PROJUCER_PATH --set-global-search-path windows defaultJuceModulePath "$JUCE_MODULES_PATH"
            
            echo "Generating Visual Studio solution..."
            & $PROJUCER_PATH --resave "MAPLE.jucer"
            
            # 솔루션 파일 확인
            if (Test-Path "Builds\VisualStudio2022\MAPLE.sln") {
                echo "Solution file generated successfully"
            } else {
                echo "Solution file not found after generation"
                exit 1
            }
        } else {
            echo "Projucer.exe not found in extracted files"
            exit 1
        }

    - name: Check Solution Path
      run: |
        echo "Checking solution file..."
        if (Test-Path ${{env.SOLUTION_FILE_PATH}}) {
            echo "Solution file exists at: ${{env.SOLUTION_FILE_PATH}}"
            dir Builds\VisualStudio2022
        } else {
            echo "Solution file not found at: ${{env.SOLUTION_FILE_PATH}}"
            exit 1
        }

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}