name: Build and Push FastAPI Image
on:
  push:
    branches:
      - maple-backend/develop
  pull_request:
    branches:
      - maple-backend/develop
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/maple-api:latest
          # 새로운 캐시 시스템 사용
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maple-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/maple-api:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1