name: Deploy to OCI Server
on:
  push:
    branches:
      - maple-deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy files to OCI server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.OCI_HOST }}
          port: ${{ secrets.OCI_PORT }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "docker-compose.yml,nginx/**"
          target: "/home/${{ secrets.OCI_USERNAME }}/deployment"
          strip_components: 0
          overwrite: true
          debug: true
      - name: Verify copied files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          port: ${{ secrets.OCI_PORT }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            echo "=== Verifying files in deployment directory ==="
            ls -la /home/${{ secrets.OCI_USERNAME }}/deployment/
            echo "=== Checking docker-compose.yml ==="
            cat /home/${{ secrets.OCI_USERNAME }}/deployment/docker-compose.yml | head -10
            echo "=== Checking nginx directory ==="
            ls -la /home/${{ secrets.OCI_USERNAME }}/deployment/nginx/
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          port: ${{ secrets.OCI_PORT }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.OCI_USERNAME }}/deployment
            
            # .env 파일 생성
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "TYPE=${{ secrets.TYPE }}" >> .env
            echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
            echo "PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}" >> .env
            echo "PRIVATE_KEY=\"${{ secrets.PRIVATE_KEY }}\"" >> .env
            echo "CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }}" >> .env
            echo "AUTH_URI=${{ secrets.AUTH_URI }}" >> .env
            echo "TOKEN_URI=${{ secrets.TOKEN_URI }}" >> .env
            echo "AUTH_PROVIDER_CERT_URL=${{ secrets.AUTH_PROVIDER_CERT_URL }}" >> .env
            echo "CLIENT_CERT_URL=${{ secrets.CLIENT_CERT_URL }}" >> .env
            echo "UNIVERSE_DOMAIN=${{ secrets.UNIVERSE_DOMAIN }}" >> .env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
            echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> .env
            echo "REACT_APP_API_URL=https://maple.ne.kr/api" >> .env
            echo "REACT_APP_SPOTIFY_CLIENT_ID=${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}" >> .env
            echo "REACT_APP_SPOTIFY_REDIRECT_URI=https://maple.ne.kr/main" >> .env
            echo "PUBLIC_URL=/" >> .env
            
            sudo docker rm -f maple-client maple-api 2>/dev/null || true
            
            sudo docker image prune -f
            sudo docker container prune -f
            
            sudo docker compose stop maple-client maple-api
            
            sudo docker image rm -f ${DOCKER_USERNAME}/maple-client:latest ${DOCKER_USERNAME}/maple-api:latest 2>/dev/null || true
            
            sudo docker compose pull --no-parallel
            
            sudo docker compose up -d --build --force-recreate