name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, maple-backend/refactor ]
  pull_request:
    branches: [ main, develop, maple-backend/refactor ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all requirements except pytest-related packages
        pip install $(grep -v "pytest" requirements.txt | xargs)
        # Install compatible pytest versions with proper quoting
        pip install "pytest>=7.0.0,<8.0.0" "pytest-asyncio==0.23.4"
        # Install additional dependencies needed for tests
        pip install email-validator aiofiles
        
    - name: Run tests
      run: |
        python -m pytest
      env:
        TYPE: ${{ secrets.TYPE }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        AUTH_URI: ${{ secrets.AUTH_URI }}
        TOKEN_URI: ${{ secrets.TOKEN_URI }}
        AUTH_PROVIDER_CERT_URL: ${{ secrets.AUTH_PROVIDER_CERT_URL }}
        CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}
        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        FILE_PATH: ${{ secrets.FILE_PATH }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        API_KEY: ${{ secrets.API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        NEXT_PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_ID }}
        NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET }}
  
  build-and-push:
    needs: test
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/maple-backend/refactor') }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/maple-app:latest

  deploy:
    needs: build-and-push
    if: ${{ success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/maple-backend/refactor') }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Oracle Cloud via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USERNAME }}
        key: ${{ secrets.OCI_SSH_KEY }}
        key_path: ""
        passphrase: ${{ secrets.OCI_SSH_KEY_PASSPHRASE }}
        port: ${{ secrets.OCI_PORT }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p ~/maple-app
          
          # Navigate to project directory
          cd ~/maple-app
          
          # Check if it's a git repository, if not clone it
          if [ ! -d .git ]; then
            echo "Directory is not a git repository. Cloning the repository..."
            # Move any existing files to a backup directory
            if [ "$(ls -A)" ]; then
              mkdir -p ~/maple-app-backup
              mv * ~/maple-app-backup/ 2>/dev/null || true
              mv .* ~/maple-app-backup/ 2>/dev/null || true
            fi
            # Clone the repository
            git clone https://github.com/kookmin-sw/capstone-2025-05.git .
          fi
          
          # Pull the latest changes
          echo "Pulling latest changes from Git repository..."
          git fetch --all
          git checkout main || git checkout develop || git checkout maple-backend/refactor
          git pull
          
          # Create the .env file
          echo "Creating .env file..."
          cat > .env << EOL
          TYPE="${{ secrets.TYPE }}"
          PROJECT_ID="${{ secrets.PROJECT_ID }}"
          PRIVATE_KEY_ID="${{ secrets.PRIVATE_KEY_ID }}"
          PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}"
          CLIENT_EMAIL="${{ secrets.CLIENT_EMAIL }}"
          CLIENT_ID="${{ secrets.CLIENT_ID }}"
          AUTH_URI="${{ secrets.AUTH_URI }}"
          TOKEN_URI="${{ secrets.TOKEN_URI }}"
          AUTH_PROVIDER_CERT_URL="${{ secrets.AUTH_PROVIDER_CERT_URL }}"
          CLIENT_CERT_URL="${{ secrets.CLIENT_CERT_URL }}"
          UNIVERSE_DOMAIN="${{ secrets.UNIVERSE_DOMAIN }}"
          FILE_PATH="${{ secrets.FILE_PATH }}"
          CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}"
          GOOGLE_REDIRECT_URI="${{ secrets.GOOGLE_REDIRECT_URI }}"
          API_KEY="${{ secrets.API_KEY }}"
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          STORAGE_BUCKET="${{ secrets.STORAGE_BUCKET }}"
          NEXT_PUBLIC_SPOTIFY_CLIENT_ID="${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_ID }}"
          NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET="${{ secrets.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET }}"
          EOL
          
          # Check if docker-compose.yml exists
          if [ ! -f "docker-compose.yml" ]; then
            echo "Creating docker-compose.yml file..."
            cat > docker-compose.yml << EOL
          version: '3'
          
          services:
            app:
              image: ${{ secrets.DOCKER_USERNAME }}/maple-app:latest
              platform: linux/amd64  # Specify platform to avoid architecture issues
              ports:
                - "8000:8000"
              environment:
                - TYPE=\${TYPE}
                - PROJECT_ID=\${PROJECT_ID}
                - PRIVATE_KEY_ID=\${PRIVATE_KEY_ID}
                - PRIVATE_KEY=\${PRIVATE_KEY}
                - CLIENT_EMAIL=\${CLIENT_EMAIL}
                - CLIENT_ID=\${CLIENT_ID}
                - AUTH_URI=\${AUTH_URI}
                - TOKEN_URI=\${TOKEN_URI}
                - AUTH_PROVIDER_CERT_URL=\${AUTH_PROVIDER_CERT_URL}
                - CLIENT_CERT_URL=\${CLIENT_CERT_URL}
                - UNIVERSE_DOMAIN=\${UNIVERSE_DOMAIN}
                - FILE_PATH=\${FILE_PATH}
                - CLIENT_SECRET=\${CLIENT_SECRET}
                - GOOGLE_REDIRECT_URI=\${GOOGLE_REDIRECT_URI}
                - API_KEY=\${API_KEY}
                - DATABASE_URL=\${DATABASE_URL}
                - STORAGE_BUCKET=\${STORAGE_BUCKET}
                - NEXT_PUBLIC_SPOTIFY_CLIENT_ID=\${NEXT_PUBLIC_SPOTIFY_CLIENT_ID}
                - NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET=\${NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET}
              restart: always
          EOL
          fi
          
          # Pull the latest Docker image with platform specification
          echo "Pulling the latest Docker image..."
          docker pull --platform linux/amd64 ${{ secrets.DOCKER_USERNAME }}/maple-app:latest
          
          # Stop and remove existing containers
          echo "Stopping and removing existing containers..."
          docker-compose down || echo "No containers to stop"
          
          # Start updated containers
          echo "Starting updated containers..."
          docker-compose up -d